'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Desing.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1206557186603844069mcol_cross_svg_hi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1206557186603844069mcol_cross.svg.hi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1217861754507811278mightyman_Button_Icons_3_svg_med() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1217861754507811278mightyman_Button_Icons_3.svg.med", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5952066() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5952066", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property abstract_background_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract-background-14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AjaxLoadingIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AjaxLoadingIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Anititle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anititle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bckimg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bckimg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property business_ppt_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business_ppt_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Refresh_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button-Refresh-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clsc0n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clsc0n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clsc0n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clsc0n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cog_icon_2_48x48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cog-icon-2-48x48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property count() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("count", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property db() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_Open1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder Open1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property formbck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("formbck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ip_icon_03_ButtonDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ip_icon_03_ButtonDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ip_icon_03_ButtonDown___Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ip_icon_03_ButtonDown - Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loader64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loader64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loading2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menubck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menubck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menubck1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menubck1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MP900439214() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MP900439214", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newopen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newopen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property query_runner_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("query_runner-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seperetor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seperetor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Settings_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ShutDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShutDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property simplebckgrnd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("simplebckgrnd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property startup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property startup1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startup1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_photo_exit_button_19354102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-photo-exit-button-19354102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_vector_exit_button_35366032() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-vector-exit-button-35366032", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Table_Column_Drop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Table Column Drop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property titleani() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("titleani", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tools1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tools1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tugu_1293180262365() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tugu_1293180262365", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
